apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-web-app
  template:
    metadata:
      labels:
        app: maven-web-app
    spec:
      containers:
      - name: maven-web-app
        image: us-central1-docker.pkg.dev/stone-trees-422304-p7/demo-app/maven-web-app:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-service
spec:
  type: NodePort
  selector:
    app: maven-web-app
  ports:
    - port: 8080  # Port on the service
      targetPort: 8080  # Port on the pods
      nodePort: 30000  # Port exposed on the nodes (change this to your desired port number)
